# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Jc0YUj35fNsjlHu8uURMof1bHyLEL_x
"""

import mlflow
import mlflow.sklearn
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import json
import os
import sys
import warnings

if __name__ == "__main__":
    warnings.filterwarnings("ignore")

    # ====== PARAMETER DARI MLPROJECT ======
    n_estimators = int(sys.argv[1]) if len(sys.argv) > 1 else 100
    max_depth = int(sys.argv[2]) if len(sys.argv) > 2 else 10
    dataset_path = sys.argv[3] if len(sys.argv) > 3 else "train_preprocessing.csv"
    test_path = sys.argv[4] if len(sys.argv) > 4 else "test_preprocessing.csv"

    # ====== LOAD DATA (RELATIVE PATH) ======
    train = pd.read_csv(dataset_path)
    test = pd.read_csv(test_path)

    X_train = train.drop("num", axis=1)
    y_train = train["num"]
    X_test = test.drop("num", axis=1)
    y_test = test["num"]

    input_example = X_train.iloc[:5]

    with mlflow.start_run():
        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            random_state=42
        )

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        acc = accuracy_score(y_test, y_pred)

        mlflow.log_param("n_estimators", n_estimators)
        mlflow.log_param("max_depth", max_depth)
        mlflow.log_metric("accuracy", acc)

        os.makedirs("model", exist_ok=True)

        # ====== CONFUSION MATRIX ======
        cm = confusion_matrix(y_test, y_pred)
        disp = ConfusionMatrixDisplay(confusion_matrix=cm)
        disp.plot()
        plt.savefig("model/confusion_matrix.png")
        mlflow.log_artifact("model/confusion_matrix.png")

        # ====== METRIC JSON ======
        with open("model/metric_info.json", "w") as f:
            json.dump({"accuracy": acc}, f)
        mlflow.log_artifact("model/metric_info.json")

        # ====== LOG MODEL ======
        mlflow.sklearn.log_model(
            sk_model=model,
            artifact_path="model",
            input_example=input_example
        )

        print("Accuracy:", acc)